import * as bookcarsTypes from ':bookcars-types'

export const mockSaleBrands = [
  { name: 'Alfa Romeo', count: 3 },
  { name: 'Audi', count: 5 },
  { name: 'Bentley', count: 1 },
  { name: 'Kia', count: 6 },
  { name: 'Renault', count: 4 },
  { name: 'Jetour', count: 2 },
]

export const mockDealerships: bookcarsTypes.Dealership[] = [
  {
    _id: 'dealer-cs-motors',
    name: 'CS Motors',
    location: 'Zouk',
    city: 'Keserwan',
    listingCount: 12,
  },
  {
    _id: 'dealer-rahme',
    name: 'Rahme Motors Division',
    location: 'Zalka, Amaret Chalhoub',
    city: 'Beirut',
    listingCount: 8,
  },
  {
    _id: 'dealer-tohme',
    name: 'Tohme Motors',
    location: 'Dbayeh',
    city: 'Metn',
    listingCount: 15,
  },
  {
    _id: 'dealer-anthony',
    name: 'Anthony Motors',
    location: 'Dekweneh',
    city: 'Metn',
    listingCount: 5,
  },
]

export const mockSaleListings: bookcarsTypes.SaleListing[] = [
  {
    _id: 'sale-1',
    title: '2019 Kia Sportage',
    brand: 'Kia',
    model: 'Sportage',
    year: 2019,
    price: 18000,
    mileage: 65000,
    gearbox: bookcarsTypes.GearboxType.Automatic,
    drivetrain: bookcarsTypes.DrivetrainType.Fwd,
    condition: bookcarsTypes.ListingCondition.Used,
    source: bookcarsTypes.ListingSource.Company,
    fuelType: bookcarsTypes.CarType.Gasoline,
    category: bookcarsTypes.SaleCategory.Suv,
    exteriorColor: 'Silver',
    colorHex: '#BFC4C7',
    city: 'Zouk',
    locationLabel: 'Zouk, Keserwan',
    description: 'Company serviced. Clean interior. Two keys and one previous owner.',
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=1200&q=80',
    ],
    features: {
      technology: ['Bluetooth', 'Backup Camera', 'Navigation'],
      safety: ['Cruise Control', 'Parking Sensors', 'ABS'],
      comfort: ['Power Windows', 'Leather Seats', 'Keyless Start'],
    },
    featured: true,
    seller: {
      type: bookcarsTypes.ListingSellerType.Dealership,
      name: 'CS Motors',
      phone: '+96170000001',
      whatsapp: '+96170000001',
      location: 'Zouk',
      supplierId: 'dealer-cs-motors',
    },
    createdAt: '2026-03-18T12:00:00.000Z',
  },
  {
    _id: 'sale-2',
    title: '2018 Renault Duster',
    brand: 'Renault',
    model: 'Duster',
    year: 2018,
    price: 10000,
    mileage: 127000,
    gearbox: bookcarsTypes.GearboxType.Automatic,
    drivetrain: bookcarsTypes.DrivetrainType.Awd,
    condition: bookcarsTypes.ListingCondition.Used,
    source: bookcarsTypes.ListingSource.Company,
    fuelType: bookcarsTypes.CarType.Gasoline,
    category: bookcarsTypes.SaleCategory.Suv,
    exteriorColor: 'Black',
    colorHex: '#191919',
    city: 'Zalka',
    locationLabel: 'Zalka, Metn',
    description: 'Company service history, one owner, AWD and ready for daily use.',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1200&q=80',
    ],
    features: {
      technology: ['Bluetooth', 'USB', 'Navigation'],
      safety: ['Parking Sensors', 'Rear Camera', 'Traction Control'],
      comfort: ['Leather Seats', 'Power Steering', 'Power Windows'],
    },
    seller: {
      type: bookcarsTypes.ListingSellerType.Private,
      name: 'Bob Chedid',
      phone: '+96170000002',
      whatsapp: '+96170000002',
      location: 'Zalka',
      badge: 'PRIVATE',
    },
    createdAt: '2026-03-10T08:00:00.000Z',
  },
  {
    _id: 'sale-3',
    title: '2024 Jetour T2',
    brand: 'Jetour',
    model: 'T2',
    year: 2024,
    price: 39500,
    mileage: 12000,
    gearbox: bookcarsTypes.GearboxType.Automatic,
    drivetrain: bookcarsTypes.DrivetrainType.FourWd,
    condition: bookcarsTypes.ListingCondition.New,
    source: bookcarsTypes.ListingSource.Gcc,
    fuelType: bookcarsTypes.CarType.Hybrid,
    category: bookcarsTypes.SaleCategory.Suv,
    exteriorColor: 'Sand',
    colorHex: '#C7B28B',
    city: 'Dbayeh',
    locationLabel: 'Dbayeh, Metn',
    description: 'Brand new stock with panoramic roof, adaptive cruise control and dealer warranty.',
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=1200&q=80',
    ],
    features: {
      technology: ['Apple CarPlay', '360 Camera', 'Wireless Charger'],
      safety: ['Lane Assist', 'Adaptive Cruise Control', 'Blind Spot Monitor'],
      comfort: ['Panoramic Roof', 'Ventilated Seats', 'Ambient Lighting'],
    },
    featured: true,
    seller: {
      type: bookcarsTypes.ListingSellerType.Dealership,
      name: 'Tohme Motors',
      phone: '+96170000003',
      whatsapp: '+96170000003',
      location: 'Dbayeh',
      supplierId: 'dealer-tohme',
    },
    createdAt: '2026-03-22T09:30:00.000Z',
  },
  {
    _id: 'sale-4',
    title: '2020 Audi A5 Sportback',
    brand: 'Audi',
    model: 'A5 Sportback',
    year: 2020,
    price: 33500,
    mileage: 54000,
    gearbox: bookcarsTypes.GearboxType.Automatic,
    drivetrain: bookcarsTypes.DrivetrainType.Awd,
    condition: bookcarsTypes.ListingCondition.Used,
    source: bookcarsTypes.ListingSource.Imported,
    fuelType: bookcarsTypes.CarType.Gasoline,
    category: bookcarsTypes.SaleCategory.Sports,
    exteriorColor: 'Gray',
    colorHex: '#7F7F82',
    city: 'Dekweneh',
    locationLabel: 'Dekweneh, Metn',
    description: 'Sharp condition, imported spec, fully loaded and ceramic protected.',
    images: [
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80',
    ],
    features: {
      technology: ['Virtual Cockpit', 'Navigation', 'Premium Audio'],
      safety: ['360 Sensors', 'Rear Camera', 'Adaptive Lights'],
      comfort: ['Heated Seats', 'Memory Seats', 'Dual Zone AC'],
    },
    seller: {
      type: bookcarsTypes.ListingSellerType.Dealership,
      name: 'Anthony Motors',
      phone: '+96170000004',
      whatsapp: '+96170000004',
      location: 'Dekweneh',
      supplierId: 'dealer-anthony',
    },
    createdAt: '2026-03-12T09:00:00.000Z',
  },
]
