import * as bookcarsTypes from ':bookcars-types'

export const mockDealerships: bookcarsTypes.Dealership[] = [
  {
    _id: 'dealer-rahme',
    name: 'Rahme Motors Division',
    location: 'Zalka, Amaret Chalhoub',
    city: 'Zalka',
    listingCount: 12,
  },
  {
    _id: 'dealer-tohme',
    name: 'Tohme Motors',
    location: 'Dbayeh',
    city: 'Dbayeh',
    listingCount: 19,
  },
  {
    _id: 'dealer-cs',
    name: 'CS Motors',
    location: 'Zouk',
    city: 'Zouk',
    listingCount: 8,
  },
]

export const mockSaleListings: bookcarsTypes.SaleListing[] = [
  {
    _id: 'sale-renault-duster-2018',
    title: '2018 Renault Duster',
    brand: 'Renault',
    model: 'Duster',
    year: 2018,
    price: 10000,
    mileage: 127000,
    gearbox: bookcarsTypes.GearboxType.Automatic,
    drivetrain: bookcarsTypes.DrivetrainType.Awd,
    condition: bookcarsTypes.ListingCondition.Used,
    source: bookcarsTypes.ListingSource.Company,
    fuelType: bookcarsTypes.CarType.Gasoline,
    category: bookcarsTypes.SaleCategory.Suv,
    exteriorColor: 'Gray',
    colorHex: '#6E7177',
    city: 'Beirut',
    locationLabel: 'Zalka',
    description: 'Company service history, one owner, clean interior, and recently serviced.',
    images: [
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    seller: {
      type: bookcarsTypes.ListingSellerType.Private,
      name: 'Bob Chedid',
      location: 'Beirut',
      badge: 'Private',
    },
    features: {
      technology: ['Bluetooth', 'Backup Camera', 'Navigation'],
      safety: ['Cruise Control', 'Parking Sensors', 'ABS'],
      comfort: ['Leather Seats', 'Power Windows', 'Keyless Entry'],
    },
    createdAt: '2026-03-10T12:00:00.000Z',
    updatedAt: '2026-03-10T12:00:00.000Z',
  },
  {
    _id: 'sale-kia-sportage-2019',
    title: '2019 Kia Sportage',
    brand: 'Kia',
    model: 'Sportage',
    year: 2019,
    price: 18000,
    mileage: 65000,
    gearbox: bookcarsTypes.GearboxType.Automatic,
    drivetrain: bookcarsTypes.DrivetrainType.Fwd,
    condition: bookcarsTypes.ListingCondition.Used,
    source: bookcarsTypes.ListingSource.Gcc,
    fuelType: bookcarsTypes.CarType.Gasoline,
    category: bookcarsTypes.SaleCategory.Suv,
    exteriorColor: 'Silver',
    colorHex: '#B8BBC1',
    city: 'Zouk',
    locationLabel: 'Zouk',
    description: 'Popular family SUV with low mileage and full dealership maintenance.',
    images: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80',
    ],
    seller: {
      type: bookcarsTypes.ListingSellerType.Dealership,
      name: 'CS Motors',
      supplierId: 'dealer-cs',
      location: 'Zouk',
    },
    features: {
      technology: ['Apple CarPlay', 'Bluetooth', 'Rear Camera'],
      safety: ['Lane Assist', 'Parking Sensors', 'Blind Spot Alert'],
      comfort: ['Heated Seats', 'Panoramic Roof', 'Dual Zone AC'],
    },
    createdAt: '2026-03-18T12:00:00.000Z',
    updatedAt: '2026-03-18T12:00:00.000Z',
  },
  {
    _id: 'sale-bmw-330i-2021',
    title: '2021 BMW 330i M Sport',
    brand: 'BMW',
    model: '330i',
    year: 2021,
    price: 39500,
    mileage: 28000,
    gearbox: bookcarsTypes.GearboxType.Automatic,
    drivetrain: bookcarsTypes.DrivetrainType.Rwd,
    condition: bookcarsTypes.ListingCondition.Used,
    source: bookcarsTypes.ListingSource.Imported,
    fuelType: bookcarsTypes.CarType.Hybrid,
    category: bookcarsTypes.SaleCategory.Sedan,
    exteriorColor: 'Black',
    colorHex: '#111111',
    city: 'Dbayeh',
    locationLabel: 'Dbayeh',
    description: 'Well optioned M Sport package with premium interior and digital cluster.',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    seller: {
      type: bookcarsTypes.ListingSellerType.Dealership,
      name: 'Tohme Motors',
      supplierId: 'dealer-tohme',
      location: 'Dbayeh',
    },
    features: {
      technology: ['Digital Cluster', 'Wireless Charging', 'Head-Up Display'],
      safety: ['Adaptive Cruise', '360 Camera', 'Collision Warning'],
      comfort: ['Memory Seats', 'Ambient Lighting', 'Sunroof'],
    },
    createdAt: '2026-03-22T12:00:00.000Z',
    updatedAt: '2026-03-22T12:00:00.000Z',
  },
  {
    _id: 'sale-jetour-t2-2026',
    title: '2026 Jetour T2',
    brand: 'Jetour',
    model: 'T2',
    year: 2026,
    price: 32000,
    mileage: 120,
    gearbox: bookcarsTypes.GearboxType.Automatic,
    drivetrain: bookcarsTypes.DrivetrainType.FourWd,
    condition: bookcarsTypes.ListingCondition.New,
    source: bookcarsTypes.ListingSource.Company,
    fuelType: bookcarsTypes.CarType.Gasoline,
    category: bookcarsTypes.SaleCategory.Suv,
    exteriorColor: 'Beige',
    colorHex: '#CBB690',
    city: 'Zalka',
    locationLabel: 'Zalka',
    description: 'Brand new arrival with aggressive styling, large infotainment, and off-road package.',
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    seller: {
      type: bookcarsTypes.ListingSellerType.Dealership,
      name: 'Rahme Motors Division',
      supplierId: 'dealer-rahme',
      location: 'Zalka',
    },
    features: {
      technology: ['Navigation', '360 Camera', 'Voice Commands'],
      safety: ['Hill Descent Control', 'Adaptive Cruise', 'Emergency Braking'],
      comfort: ['Leather Seats', 'Wireless Charging', 'Ambient Lighting'],
    },
    createdAt: '2026-03-24T12:00:00.000Z',
    updatedAt: '2026-03-24T12:00:00.000Z',
  },
]

export const mockSaleBrands = ['BMW', 'Jetour', 'Kia', 'Renault'].map((name) => ({
  name,
  count: mockSaleListings.filter((listing) => listing.brand === name).length,
}))
